
```{r}
library(ggplot2)
library(tidyverse)
library(gifski)
library(gganimate)
df=read_csv("https://bryantstats.github.io/math421/data/adult_census.csv")

df %>% ggplot(aes(x = hours.per.week,
           y = capital.loss, color=race))+
  geom_point()+
  transition_states(marital.status)+
  labs(title = 'marital.status: {closest_state}')
```
```{r}
df %>% ggplot(aes(x = sex,
                  fill=marital.status))+
  geom_bar(position = 'fill')+
  transition_states(race) +
  labs(title = 'race: {closest_state}')
```
```{r}
df=read_csv("https://covid19.who.int/WHO-COVID-19-global-data.csv")
head(df) 
```
```{r}
library(lubridate)

df$week <- month(df$Date_reported)

d1 <- df %>% group_by(week, Country) %>% summarise(sum = sum(Cumulative_deaths))
d2 <- d1 %>% group_by(week) %>% mutate(rank=rank(-sum)) 
d3 <- d2 %>% filter(rank <= 10)

a1 <- d3 %>% ggplot(aes(x=rank, y=sum, group=Country, fill=Country, label=Country)) + geom_col()+
    geom_text(aes(y = sum, label = Country), hjust = 1.4)+ 
    coord_flip(clip = "off", expand = FALSE) +scale_x_reverse()+
    labs(title = 'Month {closest_state}', x='', y='Total Number of deaths', fill='Country')+
    theme(plot.title = element_text(hjust = 1, size = 22),
          axis.ticks.y = element_blank(),
          axis.text.y  = element_blank()) + 
    transition_states(week)+
    ease_aes("cubic-in-out")
animate(a1, nframes = 400)
```
```{r}
df=read_csv("https://covidtracking.com/data/download/all-states-history.csv")
```
```{r}
df$week <- week(df$date)

d1 <- df %>% group_by(week, state) %>% summarise(sum = sum(hospitalizedCumulative))
d2 <- d1 %>% group_by(week) %>% mutate(rank=rank(-sum)) 
d3 <- d2 %>% filter(rank <= 10)

a1 <- d3 %>% ggplot(aes(x=rank, y=sum, group=state, fill=state, label=state)) + geom_col()+
    geom_text(aes(y = sum, label = state), hjust = 1.4)+ 
    coord_flip(clip = "off", expand = FALSE) +scale_x_reverse()+
    labs(title = 'week {closest_state}', x='', y='Total Number of hospitilizations', fill='state')+
    theme(plot.title = element_text(hjust = 1, size = 22),
          axis.ticks.y = element_blank(),
          axis.text.y  = element_blank()) + 
    transition_states(week)+
    ease_aes("cubic-in-out")
animate(a1, nframes = 400)
```






